<a href="https://colab.research.google.com/github/syedadilejazz/DBSCAN-Algorithm/blob/master/Text_Representation_Word_Embeddings_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:

Corpus-Entire Text
Vocabulary-Unique words in Corpus
Document-One row/One line
Word-single word

BoW → TF-IDF → Word2Vec → FastText → BERT Embeddings

Bag of words(Sklearn CountVectorizer)

In [24]:
import numpy as np
import pandas as pd

In [25]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [27]:
bow = cv.fit_transform(df['text'])
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [28]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [29]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [30]:
print(df["text"][0])
print(bow[0].toarray())

people watch dswithbappy
[[0 1 1 1 0]]

In [31]:
print(df["text"][1])
print(bow[1].toarray())

dswithbappy watch dswithbappy
[[0 2 0 1 0]]

In [32]:
print(df["text"][2])
print(bow[2].toarray())

people write comment
[[1 0 1 0 1]]

In [33]:
print(df["text"][3])
print(bow[3].toarray())

dswithbappy write comment
[[1 1 0 0 1]]

In [34]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [35]:
# new
cv.transform(['Bappy watch dswithbappy,Adil watch consistency hello']).toarray()

array([[0, 1, 0, 2, 0]])

In [36]:
# new
cv.transform(["I love AI"]).toarray()

array([[0, 0, 0, 0, 0]])

N-grams

In [41]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [42]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [43]:
bow = cv.fit_transform(df['text'])

In [44]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}

In [50]:
print(df["text"][0])
print(bow[0].toarray())

people watch dswithbappy
[[0 0 1 0 1 0]]

In [51]:
print(df["text"][1])
print(bow[1].toarray())

dswithbappy watch dswithbappy
[[1 0 0 0 1 0]]

In [52]:
print(df["text"][2])
print(bow[2].toarray())

people write comment
[[0 0 0 1 0 1]]

In [53]:
print(df["text"][3])
print(bow[3].toarray())

dswithbappy write comment
[[0 1 0 0 0 1]]

In [54]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [55]:
bow = cv.fit_transform(df['text'])

In [56]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}

In [57]:
print(df["text"][0])
print(bow[0].toarray())
print(df["text"][1])
print(bow[1].toarray())
print(df["text"][2])
print(bow[2].toarray())
print(df["text"][3])
print(bow[3].toarray())

people watch dswithbappy
[[0 0 1 0]]
dswithbappy watch dswithbappy
[[1 0 0 0]]
people write comment
[[0 0 0 1]]
dswithbappy write comment
[[0 1 0 0]]

TF-IDF (Term frequency- Inverse document frequency)

Frequent in document
BUT
Rare across documents
=
Important word

In [58]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [61]:
arr = tfid.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [62]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]

Cosine Similarity

In [63]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity
similarity = cosine_similarity(arr)

print(similarity)

[[1.         0.74515867 0.35430066 0.24682625]
 [0.74515867 1.         0.         0.42269915]
 [0.35430066 0.         1.         0.70860132]
 [0.24682625 0.42269915 0.70860132 1.        ]]

In [65]:
import pandas as pd

similarity_matrix = cosine_similarity(arr)
docs = ['D1', 'D2', 'D3', 'D4']

df_sim = pd.DataFrame(
    similarity_matrix,
    columns=docs,
    index=docs
)
print(df_sim)

          D1        D2        D3        D4
D1  1.000000  0.745159  0.354301  0.246826
D2  0.745159  1.000000  0.000000  0.422699
D3  0.354301  0.000000  1.000000  0.708601
D4  0.246826  0.422699  0.708601  1.000000

In [66]:
df=pd.read_csv("IMDB Dataset.csv")
df

ParserError: Error tokenizing data. C error: EOF inside string starting at row 12645